# Generated by Django 5.0 on 2025-10-07 21:21

import digitalizacion.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=100, unique=True)),
                ("valor", models.TextField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración del Sistema",
                "verbose_name_plural": "Configuraciones del Sistema",
                "ordering": ["clave"],
            },
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="RolUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("administrador", "Administrador"),
                            ("editor", "Editor"),
                            ("visualizador", "Visualizador"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("puede_aprobar_usuarios", models.BooleanField(default=False)),
                ("puede_editar_expedientes", models.BooleanField(default=False)),
                ("puede_ver_expedientes", models.BooleanField(default=True)),
                ("puede_crear_expedientes", models.BooleanField(default=False)),
                ("puede_eliminar_expedientes", models.BooleanField(default=False)),
                ("puede_administrar_sistema", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Rol de Usuario",
                "verbose_name_plural": "Roles de Usuario",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documentos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ArchivoAdjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("nombre_archivo", models.CharField(max_length=255)),
                ("tipo_mime", models.CharField(max_length=100)),
                ("tamaño", models.PositiveIntegerField(help_text="Tamaño en bytes")),
                ("ruta", models.CharField(max_length=500)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo Adjunto",
                "verbose_name_plural": "Archivos Adjuntos",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="AreaTipoExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre interno del área (sin espacios)",
                        max_length=100,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título visible del área", max_length=200
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Descripción opcional del área", null=True
                    ),
                ),
                (
                    "tipo_expediente",
                    models.CharField(
                        choices=[
                            ("licitacion", "Licitación"),
                            ("concurso_invitacion", "Concurso por invitación"),
                            ("compra_directa", "Compra directa"),
                            ("adjudicacion_directa", "Adjudicación directa"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subtipo_expediente",
                    models.CharField(
                        blank=True,
                        help_text="Subtipo específico del expediente (ej: bienes, servicios, arrendamientos)",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "tipo_area",
                    models.CharField(
                        choices=[
                            ("texto", "Solo Texto"),
                            ("archivo", "Subida de Archivo"),
                            ("mixto", "Texto y Archivo"),
                        ],
                        default="mixto",
                        max_length=10,
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden en que aparece en el formulario"
                    ),
                ),
                (
                    "obligatoria",
                    models.BooleanField(
                        default=True,
                        help_text="Si el área es obligatoria para completar el expediente",
                    ),
                ),
                (
                    "tipos_archivo_permitidos",
                    models.TextField(
                        blank=True,
                        help_text="Extensiones permitidas separadas por comas (ej: pdf,docx,xlsx)",
                        null=True,
                    ),
                ),
                (
                    "tamaño_max_archivo",
                    models.PositiveIntegerField(
                        default=10, help_text="Tamaño máximo de archivo en MB"
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "es_default",
                    models.BooleanField(
                        default=False, help_text="Si es un área por defecto del sistema"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "creada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Área de Tipo de Expediente",
                "verbose_name_plural": "Áreas de Tipos de Expediente",
                "ordering": [
                    "tipo_expediente",
                    "subtipo_expediente",
                    "orden",
                    "titulo",
                ],
                "unique_together": {
                    ("tipo_expediente", "subtipo_expediente", "nombre")
                },
            },
        ),
        migrations.CreateModel(
            name="CampoAreaPersonalizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre interno del campo", max_length=100
                    ),
                ),
                (
                    "etiqueta",
                    models.CharField(
                        help_text="Etiqueta visible del campo", max_length=200
                    ),
                ),
                (
                    "tipo_campo",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("textarea", "Área de Texto"),
                            ("number", "Número"),
                            ("email", "Email"),
                            ("tel", "Teléfono"),
                            ("url", "URL"),
                            ("date", "Fecha"),
                            ("time", "Hora"),
                            ("datetime", "Fecha y Hora"),
                            ("select", "Lista Desplegable"),
                            ("radio", "Botones de Radio"),
                            ("checkbox", "Casillas de Verificación"),
                            ("file", "Archivo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requerido", models.BooleanField(default=False)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "placeholder",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "opciones",
                    models.JSONField(
                        blank=True,
                        help_text='Para campos select/radio/checkbox. Formato: ["opcion1", "opcion2"]',
                        null=True,
                    ),
                ),
                (
                    "valor_minimo",
                    models.FloatField(
                        blank=True, help_text="Para campos numéricos", null=True
                    ),
                ),
                (
                    "valor_maximo",
                    models.FloatField(
                        blank=True, help_text="Para campos numéricos", null=True
                    ),
                ),
                (
                    "longitud_minima",
                    models.PositiveIntegerField(
                        blank=True, help_text="Para campos de texto", null=True
                    ),
                ),
                (
                    "longitud_maxima",
                    models.PositiveIntegerField(
                        blank=True, help_text="Para campos de texto", null=True
                    ),
                ),
                (
                    "patron_validacion",
                    models.CharField(
                        blank=True,
                        help_text="Expresión regular para validación",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campos",
                        to="digitalizacion.areatipoexpediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campo de Área Personalizado",
                "verbose_name_plural": "Campos de Áreas Personalizados",
                "ordering": ["area", "orden", "etiqueta"],
                "unique_together": {("area", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="CampoFormularioPersonalizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("etiqueta", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("textarea", "Área de texto"),
                            ("select", "Selector"),
                            ("number", "Número"),
                            ("date", "Fecha"),
                            ("email", "Email"),
                            ("file", "Archivo"),
                            ("checkbox", "Casilla de verificación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_expediente",
                    models.CharField(
                        choices=[
                            ("licitacion", "Licitación"),
                            ("concurso_invitacion", "Concurso por invitación"),
                            ("compra_directa", "Compra directa"),
                            ("adjudicacion_directa", "Adjudicación directa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requerido", models.BooleanField(default=False)),
                ("orden", models.IntegerField(default=0)),
                ("opciones", models.JSONField(blank=True, null=True)),
                (
                    "placeholder",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio"),
                            ("solicitud_area", "Solicitud del Área"),
                            ("cotizacion", "Cotización"),
                            ("requisicion_sima", "Requisición SIMA"),
                            ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                            (
                                "aprobacion_director",
                                "Aprobación Director Administrativo",
                            ),
                            ("aprobacion_secretario", "Aprobación Secretario"),
                            (
                                "notificacion_compras",
                                "Notificación a Compras Municipales",
                            ),
                            ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                            ("adjudicacion", "Adjudicación"),
                            ("formalizacion", "Formalización con Orden de Compra"),
                            ("contrato", "Contrato"),
                            ("recepcion_bien", "Recepción del Bien o Servicio"),
                            ("recepcion_facturacion", "Recepción de Facturación"),
                            ("generacion_evidencia", "Generación de Evidencia"),
                            ("envio_compras", "Envío de Expediente a Compras"),
                            ("pago", "Pago"),
                            ("completado", "Completado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="inicio",
                        max_length=30,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campo de Formulario Personalizado",
                "verbose_name_plural": "Campos de Formulario Personalizados",
                "ordering": ["tipo_expediente", "etapa", "orden", "nombre"],
                "unique_together": {("nombre", "tipo_expediente", "etapa")},
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del chat (para grupos)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("grupo", "Grupo"),
                            ("departamento", "Departamento"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("ultima_actividad", models.DateTimeField(auto_now=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participantes",
                    models.ManyToManyField(
                        related_name="chats", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "ordering": ["-ultima_actividad"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_documento", models.CharField(max_length=50, unique=True)),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("giro", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fuente_financiamiento",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "tipo_adquisicion",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "modalidad_monto",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("estado", models.CharField(default="pendiente", max_length=20)),
                ("prioridad", models.CharField(default="media", max_length=10)),
                (
                    "archivo_digital",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                ("tamaño_archivo", models.PositiveIntegerField(blank=True, null=True)),
                ("fecha_documento", models.DateField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fecha_digitalizacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("palabras_clave", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("confidencial", models.BooleanField(default=False)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalizacion.departamento",
                    ),
                ),
                (
                    "digitalizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_digitalizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_verificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalizacion.tipodocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento (Legacy)",
                "verbose_name_plural": "Documentos (Legacy)",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Expediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_expediente",
                    models.CharField(
                        blank=True,
                        help_text="Se genera automáticamente si se deja en blanco",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        help_text="Título del expediente (opcional)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del expediente (opcional)",
                        null=True,
                    ),
                ),
                (
                    "tipo_expediente",
                    models.CharField(
                        choices=[
                            ("licitacion", "Licitación"),
                            ("concurso_invitacion", "Concurso por invitación"),
                            ("compra_directa", "Compra directa"),
                            ("adjudicacion_directa", "Adjudicación directa"),
                        ],
                        help_text="Tipo de expediente",
                        max_length=20,
                    ),
                ),
                (
                    "giro",
                    models.CharField(
                        blank=True,
                        help_text="Giro del expediente (opcional)",
                        max_length=100,
                        null=True,
                        verbose_name="Giro",
                    ),
                ),
                (
                    "fuente_financiamiento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("propio_municipal", "Propio Municipal"),
                            ("estatal", "Estatal"),
                            ("federal", "Federal"),
                        ],
                        help_text="Fuente de financiamiento (opcional)",
                        max_length=20,
                        null=True,
                        verbose_name="Fuente de Financiamiento",
                    ),
                ),
                (
                    "tipo_adquisicion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bienes", "Bienes"),
                            ("servicios", "Servicios"),
                            ("arrendamientos", "Arrendamientos"),
                        ],
                        help_text="Tipo de adquisición (opcional)",
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de Adquisición",
                    ),
                ),
                (
                    "modalidad_monto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("compra_directa", "Compra Directa"),
                            ("concurso_invitacion", "Concurso por Invitación"),
                            ("licitacion", "Licitación"),
                            ("adjudicacion_directa", "Adjudicación Directa"),
                        ],
                        help_text="Modalidad de monto (opcional)",
                        max_length=30,
                        null=True,
                        verbose_name="Modalidad de Monto",
                    ),
                ),
                (
                    "subtipo_expediente",
                    models.CharField(
                        blank=True,
                        help_text="Subtipo específico que determina qué áreas usar (ej: bienes, servicios, etc.)",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "estado_actual",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio"),
                            ("solicitud_area", "Solicitud del Área"),
                            ("cotizacion", "Cotización"),
                            ("requisicion_sima", "Requisición SIMA"),
                            ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                            (
                                "aprobacion_director",
                                "Aprobación Director Administrativo",
                            ),
                            ("aprobacion_secretario", "Aprobación Secretario"),
                            (
                                "notificacion_compras",
                                "Notificación a Compras Municipales",
                            ),
                            ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                            ("adjudicacion", "Adjudicación"),
                            ("formalizacion", "Formalización con Orden de Compra"),
                            ("contrato", "Contrato"),
                            ("recepcion_bien", "Recepción del Bien o Servicio"),
                            ("recepcion_facturacion", "Recepción de Facturación"),
                            ("generacion_evidencia", "Generación de Evidencia"),
                            ("envio_compras", "Envío de Expediente a Compras"),
                            ("pago", "Pago"),
                            ("completado", "Completado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="inicio",
                        max_length=30,
                    ),
                ),
                (
                    "numero_sima",
                    models.CharField(
                        blank=True,
                        help_text="Número o código SIMA asignado al expediente",
                        max_length=50,
                        null=True,
                        verbose_name="Número SIMA",
                    ),
                ),
                (
                    "fecha_expediente",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Fecha del expediente (opcional)",
                        null=True,
                        verbose_name="Fecha del Expediente",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de vencimiento (opcional)",
                        null=True,
                        verbose_name="Fecha de Vencimiento",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del expediente"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última actualización"
                    ),
                ),
                (
                    "palabras_clave",
                    models.TextField(
                        blank=True,
                        help_text="Palabras clave separadas por comas (opcional)",
                        null=True,
                        verbose_name="Palabras Clave",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales (opcional)",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "confidencial",
                    models.BooleanField(
                        default=False,
                        help_text="¿El expediente es confidencial?",
                        verbose_name="Confidencial",
                    ),
                ),
                (
                    "motivo_rechazo",
                    models.TextField(
                        blank=True,
                        help_text="Motivo por el cual fue rechazado el expediente",
                        null=True,
                        verbose_name="Motivo de Rechazo",
                    ),
                ),
                (
                    "fecha_rechazo",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora del rechazo",
                        null=True,
                        verbose_name="Fecha de Rechazo",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        help_text="Usuario que creó el expediente",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expedientes_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        help_text="Departamento al que pertenece el expediente (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="digitalizacion.departamento",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "rechazado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que rechazó el expediente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expedientes_rechazados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Rechazado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expediente",
                "verbose_name_plural": "Expedientes",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inicio", "Inicio"),
                            ("solicitud_area", "Solicitud del Área"),
                            ("cotizacion", "Cotización"),
                            ("requisicion_sima", "Requisición SIMA"),
                            ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                            (
                                "aprobacion_director",
                                "Aprobación Director Administrativo",
                            ),
                            ("aprobacion_secretario", "Aprobación Secretario"),
                            (
                                "notificacion_compras",
                                "Notificación a Compras Municipales",
                            ),
                            ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                            ("adjudicacion", "Adjudicación"),
                            ("formalizacion", "Formalización con Orden de Compra"),
                            ("contrato", "Contrato"),
                            ("recepcion_bien", "Recepción del Bien o Servicio"),
                            ("recepcion_facturacion", "Recepción de Facturación"),
                            ("generacion_evidencia", "Generación de Evidencia"),
                            ("envio_compras", "Envío de Expediente a Compras"),
                            ("pago", "Pago"),
                            ("completado", "Completado"),
                            ("rechazado", "Rechazado"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("nombre_documento", models.CharField(max_length=200)),
                (
                    "archivo",
                    models.FileField(upload_to=digitalizacion.models.upload_to),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("tamaño_archivo", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tipo_archivo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("validado", models.BooleanField(default=False)),
                ("fecha_validacion", models.DateTimeField(blank=True, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="digitalizacion.areatipoexpediente",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_validados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="digitalizacion.expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Expediente",
                "verbose_name_plural": "Documentos de Expedientes",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="ComentarioEtapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio"),
                            ("solicitud_area", "Solicitud del Área"),
                            ("cotizacion", "Cotización"),
                            ("requisicion_sima", "Requisición SIMA"),
                            ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                            (
                                "aprobacion_director",
                                "Aprobación Director Administrativo",
                            ),
                            ("aprobacion_secretario", "Aprobación Secretario"),
                            (
                                "notificacion_compras",
                                "Notificación a Compras Municipales",
                            ),
                            ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                            ("adjudicacion", "Adjudicación"),
                            ("formalizacion", "Formalización con Orden de Compra"),
                            ("contrato", "Contrato"),
                            ("recepcion_bien", "Recepción del Bien o Servicio"),
                            ("recepcion_facturacion", "Recepción de Facturación"),
                            ("generacion_evidencia", "Generación de Evidencia"),
                            ("envio_compras", "Envío de Expediente a Compras"),
                            ("pago", "Pago"),
                            ("completado", "Completado"),
                            ("rechazado", "Rechazado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("comentario", models.TextField()),
                ("fecha_comentario", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="digitalizacion.expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario de Etapa",
                "verbose_name_plural": "Comentarios de Etapas",
                "ordering": ["-fecha_comentario"],
            },
        ),
        migrations.CreateModel(
            name="ComentarioArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        help_text="Etapa donde se hace el comentario", max_length=50
                    ),
                ),
                ("contenido", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuarios_mencionados",
                    models.ManyToManyField(
                        blank=True,
                        related_name="comentarios_mencionado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios_areas",
                        to="digitalizacion.expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario de Área",
                "verbose_name_plural": "Comentarios de Áreas",
                "ordering": ["fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="HistorialDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado_anterior",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "estado_nuevo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="digitalizacion.documento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Documento (Legacy)",
                "verbose_name_plural": "Historiales de Documentos (Legacy)",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="HistorialExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "etapa_anterior",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("etapa_nueva", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="digitalizacion.expediente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Expediente",
                "verbose_name_plural": "Historiales de Expedientes",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("archivo", "Archivo"),
                            ("icono", "Icono"),
                            ("sistema", "Sistema"),
                        ],
                        default="texto",
                        max_length=20,
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        blank=True,
                        help_text="Código del icono Bootstrap",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("leido", models.BooleanField(default=False)),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                ("fecha_lectura", models.DateTimeField(blank=True, null=True)),
                ("editado", models.BooleanField(default=False)),
                ("fecha_edicion", models.DateTimeField(blank=True, null=True)),
                (
                    "archivo_adjunto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="digitalizacion.archivoadjunto",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="digitalizacion.chat",
                    ),
                ),
                (
                    "remitente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje",
                "verbose_name_plural": "Mensajes",
                "ordering": ["fecha_envio"],
            },
        ),
        migrations.CreateModel(
            name="MensajeExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                (
                    "etiquetas",
                    models.JSONField(
                        blank=True,
                        help_text="Lista de usuarios etiquetados con @",
                        null=True,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                ("editado", models.BooleanField(default=False)),
                ("fecha_edicion", models.DateTimeField(blank=True, null=True)),
                (
                    "leido",
                    models.BooleanField(
                        default=False, help_text="Indica si el mensaje ha sido leído"
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="digitalizacion.expediente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Expediente",
                "verbose_name_plural": "Mensajes de Expedientes",
                "ordering": ["-fecha_envio"],
            },
        ),
        migrations.CreateModel(
            name="NotaExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contenido",
                    models.TextField(help_text="Contenido de la nota", max_length=500),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("amarillo", "Amarillo"),
                            ("azul", "Azul"),
                            ("verde", "Verde"),
                            ("rosa", "Rosa"),
                            ("naranja", "Naranja"),
                            ("morado", "Morado"),
                        ],
                        default="amarillo",
                        max_length=10,
                    ),
                ),
                (
                    "posicion_x",
                    models.IntegerField(
                        default=0, help_text="Posición horizontal en píxeles"
                    ),
                ),
                (
                    "posicion_y",
                    models.IntegerField(
                        default=0, help_text="Posición vertical en píxeles"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "activa",
                    models.BooleanField(
                        default=True, help_text="Si está visible o archivada"
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        help_text="Documento específico al que se adjunta la nota (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="digitalizacion.documentoexpediente",
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="digitalizacion.expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Expediente",
                "verbose_name_plural": "Notas de Expedientes",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mencion", "Mención en Post-it"),
                            ("comentario", "Nuevo Comentario"),
                            ("etapa", "Cambio de Etapa"),
                            ("documento", "Nuevo Documento"),
                            ("asignacion", "Asignación de Expediente"),
                            ("solicitud_registro", "Solicitud de Registro"),
                            ("solicitud_aprobada", "Solicitud Aprobada"),
                            ("usuario_eliminado", "Usuario Eliminado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                (
                    "enlace",
                    models.CharField(
                        blank=True,
                        help_text="URL de destino",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("leida", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_lectura", models.DateTimeField(blank=True, null=True)),
                (
                    "expediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalizacion.expediente",
                    ),
                ),
                (
                    "generada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones_generadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="PostItExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("amarillo_claro", "Amarillo Claro"),
                            ("amarillo_limon", "Amarillo Limón"),
                            ("naranja_claro", "Naranja Claro"),
                            ("naranja_suave", "Naranja Suave"),
                            ("rojo_claro", "Rojo Claro"),
                            ("rojo_suave", "Rojo Suave"),
                            ("rosa_claro", "Rosa Claro"),
                            ("rosa_suave", "Rosa Suave"),
                            ("morado_claro", "Morado Claro"),
                            ("morado_suave", "Morado Suave"),
                            ("azul_claro", "Azul Claro"),
                            ("azul_cielo", "Azul Cielo"),
                            ("azul_suave", "Azul Suave"),
                            ("verde_claro", "Verde Claro"),
                            ("verde_lima", "Verde Lima"),
                            ("verde_suave", "Verde Suave"),
                            ("turquesa_claro", "Turquesa Claro"),
                            ("turquesa_suave", "Turquesa Suave"),
                            ("gris_claro", "Gris Claro"),
                            ("gris_suave", "Gris Suave"),
                            ("beige_claro", "Beige Claro"),
                            ("beige_suave", "Beige Suave"),
                        ],
                        default="amarillo_claro",
                        max_length=20,
                    ),
                ),
                (
                    "es_urgente",
                    models.BooleanField(default=False, help_text="Marcar como urgente"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateTimeField(blank=True, null=True)),
                ("completado", models.BooleanField(default=False)),
                (
                    "menciones",
                    models.JSONField(
                        blank=True,
                        help_text="Lista de usuarios mencionados con @",
                        null=True,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postits",
                        to="digitalizacion.expediente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post-it de Expediente",
                "verbose_name_plural": "Post-its de Expedientes",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puesto", models.CharField(blank=True, max_length=100, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("extension", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "foto_perfil",
                    models.ImageField(blank=True, null=True, upload_to="perfiles/"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_ultimo_acceso", models.DateTimeField(blank=True, null=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="digitalizacion.departamento",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="digitalizacion.rolusuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
            },
        ),
        migrations.CreateModel(
            name="SolicitudRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("email_institucional", models.EmailField(max_length=254, unique=True)),
                ("puesto", models.CharField(blank=True, max_length=100, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("extension", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("motivo_rechazo", models.TextField(blank=True, null=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="digitalizacion.departamento",
                    ),
                ),
                (
                    "resuelto_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_resueltas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rol_solicitado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalizacion.rolusuario",
                    ),
                ),
                (
                    "usuario_creado",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitud_registro",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Registro",
                "verbose_name_plural": "Solicitudes de Registro",
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "last_activity",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_online", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Usuario",
                "verbose_name_plural": "Sesiones de Usuarios",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="ValorAreaExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_texto", models.TextField(blank=True, null=True)),
                ("valor_fecha", models.DateField(blank=True, null=True)),
                ("valor_datetime", models.DateTimeField(blank=True, null=True)),
                ("valor_numero", models.FloatField(blank=True, null=True)),
                ("valor_json", models.JSONField(blank=True, null=True)),
                (
                    "completada",
                    models.BooleanField(
                        default=False,
                        help_text="Si el área está marcada como completada",
                    ),
                ),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalizacion.areatipoexpediente",
                    ),
                ),
                (
                    "completada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valores_areas",
                        to="digitalizacion.expediente",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="areas_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de Área de Expediente",
                "verbose_name_plural": "Valores de Áreas de Expedientes",
                "ordering": ["expediente", "area__orden"],
                "unique_together": {("expediente", "area")},
            },
        ),
        migrations.CreateModel(
            name="EtapaExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_etapa",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio"),
                            ("solicitud_area", "Solicitud del Área"),
                            ("cotizacion", "Cotización"),
                            ("requisicion_sima", "Requisición SIMA"),
                            ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                            (
                                "aprobacion_director",
                                "Aprobación Director Administrativo",
                            ),
                            ("aprobacion_secretario", "Aprobación Secretario"),
                            (
                                "notificacion_compras",
                                "Notificación a Compras Municipales",
                            ),
                            ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                            ("adjudicacion", "Adjudicación"),
                            ("formalizacion", "Formalización con Orden de Compra"),
                            ("contrato", "Contrato"),
                            ("recepcion_bien", "Recepción del Bien o Servicio"),
                            ("recepcion_facturacion", "Recepción de Facturación"),
                            ("generacion_evidencia", "Generación de Evidencia"),
                            ("envio_compras", "Envío de Expediente a Compras"),
                            ("pago", "Pago"),
                            ("completado", "Completado"),
                            ("rechazado", "Rechazado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("completada", models.BooleanField(default=False)),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "completada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="digitalizacion.expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa de Expediente",
                "verbose_name_plural": "Etapas de Expedientes",
                "ordering": ["expediente", "nombre_etapa"],
                "unique_together": {("expediente", "nombre_etapa")},
            },
        ),
        migrations.CreateModel(
            name="ValorCampoPersonalizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalizacion.campoformulariopersonalizado",
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valores_campos_personalizados",
                        to="digitalizacion.expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de Campo Personalizado",
                "verbose_name_plural": "Valores de Campos Personalizados",
                "unique_together": {("expediente", "campo")},
            },
        ),
        migrations.CreateModel(
            name="ValorCampoPersonalizadoArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalizacion.campoareapersonalizado",
                    ),
                ),
                (
                    "valor_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valores_campos",
                        to="digitalizacion.valorareaexpediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de Campo Personalizado de Área",
                "verbose_name_plural": "Valores de Campos Personalizados de Áreas",
                "unique_together": {("valor_area", "campo")},
            },
        ),
    ]
