# Generated by Django 5.0 on 2025-10-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitalizacion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentoexpediente",
            name="area",
        ),
        migrations.AlterField(
            model_name="documentoexpediente",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("inicio", "Inicio"),
                    ("solicitud_area", "Solicitud del Área"),
                    ("cotizacion", "Cotización"),
                    ("requisicion_sima", "Requisición SIMA"),
                    ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                    ("aprobacion_director", "Aprobación Director Administrativo"),
                    ("aprobacion_secretario", "Aprobación Secretario"),
                    ("notificacion_compras", "Notificación a Compras Municipales"),
                    ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                    ("adjudicacion", "Adjudicación"),
                    ("formalizacion", "Formalización con Orden de Compra"),
                    ("contrato", "Contrato"),
                    ("recepcion_bien", "Recepción del Bien o Servicio"),
                    ("recepcion_facturacion", "Recepción de Facturación"),
                    ("generacion_evidencia", "Generación de Evidencia"),
                    ("envio_compras", "Envío de Expediente a Compras"),
                    ("pago", "Pago"),
                    ("completado", "Completado"),
                    ("rechazado", "Rechazado"),
                ],
                max_length=30,
            ),
        ),
    ]
