# Generated by Django 5.0 on 2025-10-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitalizacion", "0002_remove_documentoexpediente_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoexpediente",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="Área específica a la que pertenece este documento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos",
                to="digitalizacion.areatipoexpediente",
            ),
        ),
    ]
