# Generated by Django 4.2.6 on 2023-10-15 15:24

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone

def actualizar_estado_expediente(apps, schema_editor):
    """
    Función para actualizar el estado de los expedientes basado en el progreso de sus áreas.
    """
    Expediente = apps.get_model('digitalizacion', 'Expediente')
    AreaTipoExpediente = apps.get_model('digitalizacion', 'AreaTipoExpediente')
    ValorAreaExpediente = apps.get_model('digitalizacion', 'ValorAreaExpediente')
    
    for expediente in Expediente.objects.all():
        # Obtener todas las áreas obligatorias para este tipo de expediente
        areas_obligatorias = AreaTipoExpediente.objects.filter(
            tipo_expediente=expediente.tipo_expediente,
            obligatoria=True,
            activa=True
        )
        
        if not areas_obligatorias.exists():
            continue
            
        # Contar áreas obligatorias completadas
        areas_completadas = ValorAreaExpediente.objects.filter(
            expediente=expediente,
            area__in=areas_obligatorias,
            completada=True
        ).count()
        
        # Si todas las áreas obligatorias están completas, actualizar el estado
        if areas_completadas >= areas_obligatorias.count() and expediente.estado_actual != 'completado':
            expediente.estado_actual = 'completado'
            expediente.save(update_fields=['estado_actual'])

class Migration(migrations.Migration):

    dependencies = [
        ('digitalizacion', '0006_alter_historialexpediente_usuario'),
    ]

    operations = [
        migrations.RunPython(actualizar_estado_expediente, migrations.RunPython.noop),
    ]
