# Generated by Django 4.2.7 on 2025-03-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalizacion', '0007_auto_20231015_0924'),  # Última migración existente
    ]

    operations = [
        migrations.RemoveField(
            model_name='postitexpediente',
            name='expediente',
        ),
        migrations.RemoveField(
            model_name='postitexpediente',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='PostItExpediente',
        ),
    ]
