# Generated by Django 5.0 on 2025-10-16 20:48

from django.db import migrations, models


def set_default_estado(apps, schema_editor):
    # Establecer 'borrador' como valor por defecto para expedientes existentes
    Expediente = apps.get_model('digitalizacion', 'Expediente')
    Expediente.objects.all().update(estado='borrador')


class Migration(migrations.Migration):

    dependencies = [
        ("digitalizacion", "0010_remove_postitexpediente"),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='estado',
            field=models.CharField(
                choices=[
                    ('borrador', 'Borrador'),
                    ('en_revision', 'En Revisión'),
                    ('aprobado', 'Aprobado'),
                    ('rechazado', 'Rechazado'),
                    ('finalizado', 'Finalizado'),
                    ('archivado', 'Archivado'),
                ],
                default='borrador',
                help_text='Estado actual del expediente',
                max_length=20,
            ),
        ),
        migrations.RunPython(set_default_estado, migrations.RunPython.noop),
    ]
