# Generated by Django 5.0 on 2025-10-17 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitalizacion", "0011_add_estado_to_expediente"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="areatipoexpediente",
            options={
                "ordering": [
                    "tipo_expediente",
                    "subtipo_expediente",
                    "orden",
                    "titulo",
                ],
                "verbose_name": "Ã\x81rea de Tipo de Expediente",
                "verbose_name_plural": "Ã\x81reas de Tipos de Expediente",
            },
        ),
        migrations.AlterModelOptions(
            name="campoareapersonalizado",
            options={
                "ordering": ["area", "orden", "etiqueta"],
                "verbose_name": "Campo de Ã\x81rea Personalizado",
                "verbose_name_plural": "Campos de Ã\x81reas Personalizados",
            },
        ),
        migrations.AlterModelOptions(
            name="comentarioarea",
            options={
                "ordering": ["fecha_creacion"],
                "verbose_name": "Comentario de Ã\x81rea",
                "verbose_name_plural": "Comentarios de Ã\x81reas",
            },
        ),
        migrations.AlterModelOptions(
            name="configuracionsistema",
            options={
                "ordering": ["clave"],
                "verbose_name": "ConfiguraciÃ³n del Sistema",
                "verbose_name_plural": "Configuraciones del Sistema",
            },
        ),
        migrations.AlterModelOptions(
            name="notificacion",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "NotificaciÃ³n",
                "verbose_name_plural": "Notificaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="usersession",
            options={
                "ordering": ["-last_activity"],
                "verbose_name": "SesiÃ³n de Usuario",
                "verbose_name_plural": "Sesiones de Usuarios",
            },
        ),
        migrations.AlterModelOptions(
            name="valorareaexpediente",
            options={
                "ordering": ["expediente", "area__orden"],
                "verbose_name": "Valor de Ã\x81rea de Expediente",
                "verbose_name_plural": "Valores de Ã\x81reas de Expedientes",
            },
        ),
        migrations.AlterModelOptions(
            name="valorcampopersonalizadoarea",
            options={
                "verbose_name": "Valor de Campo Personalizado de Ã\x81rea",
                "verbose_name_plural": "Valores de Campos Personalizados de Ã\x81reas",
            },
        ),
        migrations.RenameField(
            model_name="archivoadjunto",
            old_name="tamaño",
            new_name="tamano",
        ),
        migrations.RenameField(
            model_name="documento",
            old_name="tamaño_archivo",
            new_name="tamano_archivo",
        ),
        migrations.AlterField(
            model_name="areatipoexpediente",
            name="descripcion",
            field=models.TextField(
                blank=True, help_text="DescripciÃ³n opcional del Ã¡rea", null=True
            ),
        ),
        migrations.AlterField(
            model_name="areatipoexpediente",
            name="es_default",
            field=models.BooleanField(
                default=False, help_text="Si es un Ã¡rea por defecto del sistema"
            ),
        ),
        migrations.AlterField(
            model_name="areatipoexpediente",
            name="nombre",
            field=models.CharField(
                help_text="Nombre interno del Ã¡rea (sin espacios)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="areatipoexpediente",
            name="obligatoria",
            field=models.BooleanField(
                default=True,
                help_text="Si el Ã¡rea es obligatoria para completar el expediente",
            ),
        ),
        migrations.AlterField(
            model_name="areatipoexpediente",
            name="subtipo_expediente",
            field=models.CharField(
                blank=True,
                help_text="Subtipo especÃ\xadfico del expediente (ej: bienes, servicios, arrendamientos)",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="areatipoexpediente",
            name="tipo_expediente",
            field=models.CharField(
                choices=[
                    ("licitacion", "LicitaciÃ³n"),
                    ("concurso_invitacion", "Concurso por invitaciÃ³n"),
                    ("compra_directa", "Compra directa"),
                    ("adjudicacion_directa", "AdjudicaciÃ³n directa"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="areatipoexpediente",
            name="titulo",
            field=models.CharField(
                help_text="TÃ\xadtulo visible del Ã¡rea", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="campoareapersonalizado",
            name="patron_validacion",
            field=models.CharField(
                blank=True,
                help_text="ExpresiÃ³n regular para validaciÃ³n",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="campoareapersonalizado",
            name="tipo_campo",
            field=models.CharField(
                choices=[
                    ("text", "Texto"),
                    ("textarea", "Ã\x81rea de Texto"),
                    ("number", "NÃºmero"),
                    ("email", "Email"),
                    ("tel", "TelÃ©fono"),
                    ("url", "URL"),
                    ("date", "Fecha"),
                    ("time", "Hora"),
                    ("datetime", "Fecha y Hora"),
                    ("select", "Lista Desplegable"),
                    ("radio", "Botones de Radio"),
                    ("checkbox", "Casillas de VerificaciÃ³n"),
                    ("file", "Archivo"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campoareapersonalizado",
            name="valor_maximo",
            field=models.FloatField(
                blank=True, help_text="Para campos numÃ©ricos", null=True
            ),
        ),
        migrations.AlterField(
            model_name="campoareapersonalizado",
            name="valor_minimo",
            field=models.FloatField(
                blank=True, help_text="Para campos numÃ©ricos", null=True
            ),
        ),
        migrations.AlterField(
            model_name="campoformulariopersonalizado",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("inicio", "Inicio"),
                    ("solicitud_area", "Solicitud del Ã\x81rea"),
                    ("cotizacion", "CotizaciÃ³n"),
                    ("requisicion_sima", "RequisiciÃ³n SIMA"),
                    ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                    ("aprobacion_director", "AprobaciÃ³n Director Administrativo"),
                    ("aprobacion_secretario", "AprobaciÃ³n Secretario"),
                    ("notificacion_compras", "NotificaciÃ³n a Compras Municipales"),
                    ("valoracion_tipo", "ValoraciÃ³n para Tipo de AdquisiciÃ³n"),
                    ("adjudicacion", "AdjudicaciÃ³n"),
                    ("formalizacion", "FormalizaciÃ³n con Orden de Compra"),
                    ("contrato", "Contrato"),
                    ("recepcion_bien", "RecepciÃ³n del Bien o Servicio"),
                    ("recepcion_facturacion", "RecepciÃ³n de FacturaciÃ³n"),
                    ("generacion_evidencia", "GeneraciÃ³n de Evidencia"),
                    ("envio_compras", "EnvÃ\xado de Expediente a Compras"),
                    ("pago", "Pago"),
                    ("completado", "Completado"),
                    ("rechazado", "Rechazado"),
                ],
                default="inicio",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="campoformulariopersonalizado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("text", "Texto"),
                    ("textarea", "Ã\x81rea de texto"),
                    ("select", "Selector"),
                    ("number", "NÃºmero"),
                    ("date", "Fecha"),
                    ("email", "Email"),
                    ("file", "Archivo"),
                    ("checkbox", "Casilla de verificaciÃ³n"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campoformulariopersonalizado",
            name="tipo_expediente",
            field=models.CharField(
                choices=[
                    ("licitacion", "LicitaciÃ³n"),
                    ("concurso_invitacion", "Concurso por invitaciÃ³n"),
                    ("compra_directa", "Compra directa"),
                    ("adjudicacion_directa", "AdjudicaciÃ³n directa"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="comentarioetapa",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("inicio", "Inicio"),
                    ("solicitud_area", "Solicitud del Ã\x81rea"),
                    ("cotizacion", "CotizaciÃ³n"),
                    ("requisicion_sima", "RequisiciÃ³n SIMA"),
                    ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                    ("aprobacion_director", "AprobaciÃ³n Director Administrativo"),
                    ("aprobacion_secretario", "AprobaciÃ³n Secretario"),
                    ("notificacion_compras", "NotificaciÃ³n a Compras Municipales"),
                    ("valoracion_tipo", "ValoraciÃ³n para Tipo de AdquisiciÃ³n"),
                    ("adjudicacion", "AdjudicaciÃ³n"),
                    ("formalizacion", "FormalizaciÃ³n con Orden de Compra"),
                    ("contrato", "Contrato"),
                    ("recepcion_bien", "RecepciÃ³n del Bien o Servicio"),
                    ("recepcion_facturacion", "RecepciÃ³n de FacturaciÃ³n"),
                    ("generacion_evidencia", "GeneraciÃ³n de Evidencia"),
                    ("envio_compras", "EnvÃ\xado de Expediente a Compras"),
                    ("pago", "Pago"),
                    ("completado", "Completado"),
                    ("rechazado", "Rechazado"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="documentoexpediente",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="Ã\x81rea especÃ\xadfica a la que pertenece este documento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos",
                to="digitalizacion.areatipoexpediente",
            ),
        ),
        migrations.AlterField(
            model_name="documentoexpediente",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("inicio", "Inicio"),
                    ("solicitud_area", "Solicitud del Ã\x81rea"),
                    ("cotizacion", "CotizaciÃ³n"),
                    ("requisicion_sima", "RequisiciÃ³n SIMA"),
                    ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                    ("aprobacion_director", "AprobaciÃ³n Director Administrativo"),
                    ("aprobacion_secretario", "AprobaciÃ³n Secretario"),
                    ("notificacion_compras", "NotificaciÃ³n a Compras Municipales"),
                    ("valoracion_tipo", "ValoraciÃ³n para Tipo de AdquisiciÃ³n"),
                    ("adjudicacion", "AdjudicaciÃ³n"),
                    ("formalizacion", "FormalizaciÃ³n con Orden de Compra"),
                    ("contrato", "Contrato"),
                    ("recepcion_bien", "RecepciÃ³n del Bien o Servicio"),
                    ("recepcion_facturacion", "RecepciÃ³n de FacturaciÃ³n"),
                    ("generacion_evidencia", "GeneraciÃ³n de Evidencia"),
                    ("envio_compras", "EnvÃ\xado de Expediente a Compras"),
                    ("pago", "Pago"),
                    ("completado", "Completado"),
                    ("rechazado", "Rechazado"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="etapaexpediente",
            name="nombre_etapa",
            field=models.CharField(
                choices=[
                    ("inicio", "Inicio"),
                    ("solicitud_area", "Solicitud del Ã\x81rea"),
                    ("cotizacion", "CotizaciÃ³n"),
                    ("requisicion_sima", "RequisiciÃ³n SIMA"),
                    ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                    ("aprobacion_director", "AprobaciÃ³n Director Administrativo"),
                    ("aprobacion_secretario", "AprobaciÃ³n Secretario"),
                    ("notificacion_compras", "NotificaciÃ³n a Compras Municipales"),
                    ("valoracion_tipo", "ValoraciÃ³n para Tipo de AdquisiciÃ³n"),
                    ("adjudicacion", "AdjudicaciÃ³n"),
                    ("formalizacion", "FormalizaciÃ³n con Orden de Compra"),
                    ("contrato", "Contrato"),
                    ("recepcion_bien", "RecepciÃ³n del Bien o Servicio"),
                    ("recepcion_facturacion", "RecepciÃ³n de FacturaciÃ³n"),
                    ("generacion_evidencia", "GeneraciÃ³n de Evidencia"),
                    ("envio_compras", "EnvÃ\xado de Expediente a Compras"),
                    ("pago", "Pago"),
                    ("completado", "Completado"),
                    ("rechazado", "Rechazado"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="confidencial",
            field=models.BooleanField(
                default=False,
                help_text="Â¿El expediente es confidencial?",
                verbose_name="Confidencial",
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="creado_por",
            field=models.ForeignKey(
                help_text="Usuario que creÃ³ el expediente",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expedientes_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="DescripciÃ³n del expediente (opcional)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="estado",
            field=models.CharField(
                choices=[
                    ("en_proceso", "En proceso"),
                    ("completo", "Expediente completo"),
                    ("rechazado", "Rechazado"),
                ],
                default="en_proceso",
                help_text="Estado actual del expediente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="estado_actual",
            field=models.CharField(
                choices=[
                    ("inicio", "Inicio"),
                    ("solicitud_area", "Solicitud del Ã\x81rea"),
                    ("cotizacion", "CotizaciÃ³n"),
                    ("requisicion_sima", "RequisiciÃ³n SIMA"),
                    ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                    ("aprobacion_director", "AprobaciÃ³n Director Administrativo"),
                    ("aprobacion_secretario", "AprobaciÃ³n Secretario"),
                    ("notificacion_compras", "NotificaciÃ³n a Compras Municipales"),
                    ("valoracion_tipo", "ValoraciÃ³n para Tipo de AdquisiciÃ³n"),
                    ("adjudicacion", "AdjudicaciÃ³n"),
                    ("formalizacion", "FormalizaciÃ³n con Orden de Compra"),
                    ("contrato", "Contrato"),
                    ("recepcion_bien", "RecepciÃ³n del Bien o Servicio"),
                    ("recepcion_facturacion", "RecepciÃ³n de FacturaciÃ³n"),
                    ("generacion_evidencia", "GeneraciÃ³n de Evidencia"),
                    ("envio_compras", "EnvÃ\xado de Expediente a Compras"),
                    ("pago", "Pago"),
                    ("completado", "Completado"),
                    ("rechazado", "Rechazado"),
                ],
                default="inicio",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="fecha_actualizacion",
            field=models.DateTimeField(
                auto_now=True, help_text="Fecha de Ãºltima actualizaciÃ³n"
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Fecha de creaciÃ³n del expediente"
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="modalidad_monto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compra_directa", "Compra Directa"),
                    ("concurso_invitacion", "Concurso por InvitaciÃ³n"),
                    ("licitacion", "LicitaciÃ³n"),
                    ("adjudicacion_directa", "AdjudicaciÃ³n Directa"),
                ],
                help_text="Modalidad de monto (opcional)",
                max_length=30,
                null=True,
                verbose_name="Modalidad de Monto",
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="numero_expediente",
            field=models.CharField(
                blank=True,
                help_text="Se genera automÃ¡ticamente si se deja en blanco",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="numero_sima",
            field=models.CharField(
                blank=True,
                help_text="NÃºmero o cÃ³digo SIMA asignado al expediente",
                max_length=50,
                null=True,
                verbose_name="NÃºmero SIMA",
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="rechazado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que rechazÃ³ el expediente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expedientes_rechazados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Rechazado por",
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="subtipo_expediente",
            field=models.CharField(
                blank=True,
                help_text="Subtipo especÃ\xadfico que determina quÃ© Ã¡reas usar (ej: bienes, servicios, etc.)",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="tipo_adquisicion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bienes", "Bienes"),
                    ("servicios", "Servicios"),
                    ("arrendamientos", "Arrendamientos"),
                ],
                help_text="Tipo de adquisiciÃ³n (opcional)",
                max_length=20,
                null=True,
                verbose_name="Tipo de AdquisiciÃ³n",
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="tipo_expediente",
            field=models.CharField(
                choices=[
                    ("licitacion", "LicitaciÃ³n"),
                    ("concurso_invitacion", "Concurso por invitaciÃ³n"),
                    ("compra_directa", "Compra directa"),
                    ("adjudicacion_directa", "AdjudicaciÃ³n directa"),
                ],
                help_text="Tipo de expediente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="titulo",
            field=models.CharField(
                blank=True,
                help_text="TÃ\xadtulo del expediente (opcional)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historialexpediente",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Usuario que realizó la acción",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mensaje",
            name="icono",
            field=models.CharField(
                blank=True,
                help_text="CÃ³digo del icono Bootstrap",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mensajeexpediente",
            name="leido",
            field=models.BooleanField(
                default=False, help_text="Indica si el mensaje ha sido leÃ\xaddo"
            ),
        ),
        migrations.AlterField(
            model_name="notaexpediente",
            name="activa",
            field=models.BooleanField(
                default=True, help_text="Si estÃ¡ visible o archivada"
            ),
        ),
        migrations.AlterField(
            model_name="notaexpediente",
            name="documento",
            field=models.ForeignKey(
                blank=True,
                help_text="Documento especÃ\xadfico al que se adjunta la nota (opcional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas",
                to="digitalizacion.documentoexpediente",
            ),
        ),
        migrations.AlterField(
            model_name="notaexpediente",
            name="posicion_x",
            field=models.IntegerField(
                default=0, help_text="PosiciÃ³n horizontal en pÃ\xadxeles"
            ),
        ),
        migrations.AlterField(
            model_name="notaexpediente",
            name="posicion_y",
            field=models.IntegerField(
                default=0, help_text="PosiciÃ³n vertical en pÃ\xadxeles"
            ),
        ),
        migrations.AlterField(
            model_name="notificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("mencion", "MenciÃ³n en Post-it"),
                    ("comentario", "Nuevo Comentario"),
                    ("etapa", "Cambio de Etapa"),
                    ("documento", "Nuevo Documento"),
                    ("asignacion", "AsignaciÃ³n de Expediente"),
                    ("solicitud_registro", "Solicitud de Registro"),
                    ("solicitud_aprobada", "Solicitud Aprobada"),
                    ("usuario_eliminado", "Usuario Eliminado"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="valorareaexpediente",
            name="completada",
            field=models.BooleanField(
                default=False, help_text="Si el Ã¡rea estÃ¡ marcada como completada"
            ),
        ),
    ]
