# Generated by Django 5.0 on 2025-10-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitalizacion", "0013_alter_campoformulariopersonalizado_etapa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expediente",
            name="fuente_financiamiento",
            field=models.CharField(
                choices=[
                    ("propio_municipal", "Propio Municipal"),
                    ("estatal", "Estatal"),
                    ("federal", "Federal"),
                ],
                default="propio_municipal",
                help_text="Fuente de financiamiento del expediente",
                max_length=20,
                verbose_name="Fuente de Financiamiento",
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="tipo_adquisicion",
            field=models.CharField(
                choices=[
                    ("bienes", "Bienes"),
                    ("servicios", "Servicios"),
                    ("arrendamientos", "Arrendamientos"),
                ],
                default="bienes",
                help_text="Tipo de adquisiciÃ³n del expediente",
                max_length=20,
                verbose_name="Tipo de AdquisiciÃ³n",
            ),
        ),
    ]
