# Generated by Django 5.0 on 2025-10-20 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitalizacion", "0014_alter_expediente_fuente_financiamiento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expediente",
            name="progreso",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Porcentaje de completado del expediente (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="fuente_financiamiento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("propio_municipal", "Propio Municipal"),
                    ("estatal", "Estatal"),
                    ("federal", "Federal"),
                ],
                help_text="Fuente de financiamiento del expediente (solo para ciertos tipos de expediente)",
                max_length=20,
                null=True,
                verbose_name="Fuente de Financiamiento",
            ),
        ),
    ]
