# Generated by Django 5.0 on 2025-10-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitalizacion", "0015_expediente_progreso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areatipoexpediente",
            name="descripcion",
            field=models.TextField(
                blank=True, help_text="Descripción opcional del área", null=True
            ),
        ),
        migrations.AlterField(
            model_name="areatipoexpediente",
            name="nombre",
            field=models.CharField(
                help_text="Nombre interno del área (sin espacios)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="areatipoexpediente",
            name="subtipo_expediente",
            field=models.CharField(
                blank=True,
                help_text="Subtipo específico del expediente (ej: bienes, servicios, arrendamientos)",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="areatipoexpediente",
            name="tipo_expediente",
            field=models.CharField(
                choices=[
                    ("licitacion", "Licitación"),
                    ("concurso_invitacion", "Concurso por invitación"),
                    ("compra_directa", "Compra directa"),
                    ("adjudicacion_directa", "Adjudicación directa"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="areatipoexpediente",
            name="titulo",
            field=models.CharField(help_text="Título visible del área", max_length=200),
        ),
        migrations.AlterField(
            model_name="campoformulariopersonalizado",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("inicio", "Inicio"),
                    ("solicitud_area", "Solicitud del Área"),
                    ("cotizacion", "Cotización"),
                    ("requisicion_sima", "Requisición SIMA"),
                    ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                    ("aprobacion_director", "Aprobación Director Administrativo"),
                    ("aprobacion_secretario", "Aprobación Secretario"),
                    ("notificacion_compras", "Notificación a Compras Municipales"),
                    ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                    ("adjudicacion", "Adjudicación"),
                    ("formalizacion", "Formalización con Orden de Compra"),
                    ("contrato", "Contrato"),
                    ("recepcion_bien", "Recepción del Bien o Servicio"),
                    ("recepcion_facturacion", "Recepción de Facturación"),
                    ("generacion_evidencia", "Generación de Evidencia"),
                    ("envio_compras", "Envío de Expediente a Compras"),
                    ("pago", "Pago"),
                    ("completado", "Completado"),
                    ("rechazado", "Rechazado"),
                    ("oficio_control_patrimonial", "Oficio de Control Patrimonial"),
                ],
                default="inicio",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="campoformulariopersonalizado",
            name="tipo_expediente",
            field=models.CharField(
                choices=[
                    ("licitacion", "Licitación"),
                    ("concurso_invitacion", "Concurso por invitación"),
                    ("compra_directa", "Compra directa"),
                    ("adjudicacion_directa", "Adjudicación directa"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="comentarioetapa",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("inicio", "Inicio"),
                    ("solicitud_area", "Solicitud del Área"),
                    ("cotizacion", "Cotización"),
                    ("requisicion_sima", "Requisición SIMA"),
                    ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                    ("aprobacion_director", "Aprobación Director Administrativo"),
                    ("aprobacion_secretario", "Aprobación Secretario"),
                    ("notificacion_compras", "Notificación a Compras Municipales"),
                    ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                    ("adjudicacion", "Adjudicación"),
                    ("formalizacion", "Formalización con Orden de Compra"),
                    ("contrato", "Contrato"),
                    ("recepcion_bien", "Recepción del Bien o Servicio"),
                    ("recepcion_facturacion", "Recepción de Facturación"),
                    ("generacion_evidencia", "Generación de Evidencia"),
                    ("envio_compras", "Envío de Expediente a Compras"),
                    ("pago", "Pago"),
                    ("completado", "Completado"),
                    ("rechazado", "Rechazado"),
                    ("oficio_control_patrimonial", "Oficio de Control Patrimonial"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="documentoexpediente",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("inicio", "Inicio"),
                    ("solicitud_area", "Solicitud del Área"),
                    ("cotizacion", "Cotización"),
                    ("requisicion_sima", "Requisición SIMA"),
                    ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                    ("aprobacion_director", "Aprobación Director Administrativo"),
                    ("aprobacion_secretario", "Aprobación Secretario"),
                    ("notificacion_compras", "Notificación a Compras Municipales"),
                    ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                    ("adjudicacion", "Adjudicación"),
                    ("formalizacion", "Formalización con Orden de Compra"),
                    ("contrato", "Contrato"),
                    ("recepcion_bien", "Recepción del Bien o Servicio"),
                    ("recepcion_facturacion", "Recepción de Facturación"),
                    ("generacion_evidencia", "Generación de Evidencia"),
                    ("envio_compras", "Envío de Expediente a Compras"),
                    ("pago", "Pago"),
                    ("completado", "Completado"),
                    ("rechazado", "Rechazado"),
                    ("oficio_control_patrimonial", "Oficio de Control Patrimonial"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="etapaexpediente",
            name="nombre_etapa",
            field=models.CharField(
                choices=[
                    ("inicio", "Inicio"),
                    ("solicitud_area", "Solicitud del Área"),
                    ("cotizacion", "Cotización"),
                    ("requisicion_sima", "Requisición SIMA"),
                    ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                    ("aprobacion_director", "Aprobación Director Administrativo"),
                    ("aprobacion_secretario", "Aprobación Secretario"),
                    ("notificacion_compras", "Notificación a Compras Municipales"),
                    ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                    ("adjudicacion", "Adjudicación"),
                    ("formalizacion", "Formalización con Orden de Compra"),
                    ("contrato", "Contrato"),
                    ("recepcion_bien", "Recepción del Bien o Servicio"),
                    ("recepcion_facturacion", "Recepción de Facturación"),
                    ("generacion_evidencia", "Generación de Evidencia"),
                    ("envio_compras", "Envío de Expediente a Compras"),
                    ("pago", "Pago"),
                    ("completado", "Completado"),
                    ("rechazado", "Rechazado"),
                    ("oficio_control_patrimonial", "Oficio de Control Patrimonial"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="estado_actual",
            field=models.CharField(
                choices=[
                    ("inicio", "Inicio"),
                    ("solicitud_area", "Solicitud del Área"),
                    ("cotizacion", "Cotización"),
                    ("requisicion_sima", "Requisición SIMA"),
                    ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                    ("aprobacion_director", "Aprobación Director Administrativo"),
                    ("aprobacion_secretario", "Aprobación Secretario"),
                    ("notificacion_compras", "Notificación a Compras Municipales"),
                    ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                    ("adjudicacion", "Adjudicación"),
                    ("formalizacion", "Formalización con Orden de Compra"),
                    ("contrato", "Contrato"),
                    ("recepcion_bien", "Recepción del Bien o Servicio"),
                    ("recepcion_facturacion", "Recepción de Facturación"),
                    ("generacion_evidencia", "Generación de Evidencia"),
                    ("envio_compras", "Envío de Expediente a Compras"),
                    ("pago", "Pago"),
                    ("completado", "Completado"),
                    ("rechazado", "Rechazado"),
                    ("oficio_control_patrimonial", "Oficio de Control Patrimonial"),
                ],
                default="inicio",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="tipo_expediente",
            field=models.CharField(
                choices=[
                    ("licitacion", "Licitación"),
                    ("concurso_invitacion", "Concurso por invitación"),
                    ("compra_directa", "Compra directa"),
                    ("adjudicacion_directa", "Adjudicación directa"),
                ],
                help_text="Tipo de expediente",
                max_length=20,
            ),
        ),
    ]
