# Generated by Django 5.0 on 2025-12-06 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitalizacion", "0016_alter_areatipoexpediente_descripcion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="areatipoexpediente",
            options={
                "ordering": [
                    "tipo_expediente",
                    "subtipo_expediente",
                    "orden",
                    "titulo",
                ],
                "verbose_name": "Área de Tipo de Expediente",
                "verbose_name_plural": "Áreas de Tipos de Expediente",
            },
        ),
        migrations.AlterModelOptions(
            name="campoareapersonalizado",
            options={
                "ordering": ["area", "orden", "etiqueta"],
                "verbose_name": "Campo de Área Personalizado",
                "verbose_name_plural": "Campos de Áreas Personalizados",
            },
        ),
        migrations.AlterModelOptions(
            name="comentarioarea",
            options={
                "ordering": ["fecha_creacion"],
                "verbose_name": "Comentario de área",
                "verbose_name_plural": "Comentarios de áreas",
            },
        ),
        migrations.AlterModelOptions(
            name="notificacion",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="usersession",
            options={
                "ordering": ["-last_activity"],
                "verbose_name": "Sesión de Usuario",
                "verbose_name_plural": "Sesiones de Usuarios",
            },
        ),
        migrations.AlterModelOptions(
            name="valorareaexpediente",
            options={
                "ordering": ["expediente", "area__orden"],
                "verbose_name": "Valor de Área de Expediente",
                "verbose_name_plural": "Valores de Áreas de Expedientes",
            },
        ),
        migrations.AlterModelOptions(
            name="valorcampopersonalizadoarea",
            options={
                "verbose_name": "Valor de Campo Personalizado de Área",
                "verbose_name_plural": "Valores de Campos Personalizados de Áreas",
            },
        ),
        migrations.AlterField(
            model_name="areatipoexpediente",
            name="es_default",
            field=models.BooleanField(
                default=False, help_text="Si es un área por defecto del sistema"
            ),
        ),
        migrations.AlterField(
            model_name="areatipoexpediente",
            name="obligatoria",
            field=models.BooleanField(
                default=True,
                help_text="Si el área es obligatoria para completar el expediente",
            ),
        ),
        migrations.AlterField(
            model_name="campoareapersonalizado",
            name="patron_validacion",
            field=models.CharField(
                blank=True,
                help_text="Expresión regular para validación",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="campoareapersonalizado",
            name="tipo_campo",
            field=models.CharField(
                choices=[
                    ("text", "Texto"),
                    ("textarea", "Área de Texto"),
                    ("number", "Número"),
                    ("email", "Email"),
                    ("tel", "Teléfono"),
                    ("url", "URL"),
                    ("date", "Fecha"),
                    ("time", "Hora"),
                    ("datetime", "Fecha y Hora"),
                    ("select", "Lista Desplegable"),
                    ("radio", "Botones de Radio"),
                    ("checkbox", "Casillas de Verificación"),
                    ("file", "Archivo"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campoareapersonalizado",
            name="valor_maximo",
            field=models.FloatField(
                blank=True, help_text="Para campos numéricos", null=True
            ),
        ),
        migrations.AlterField(
            model_name="campoareapersonalizado",
            name="valor_minimo",
            field=models.FloatField(
                blank=True, help_text="Para campos numéricos", null=True
            ),
        ),
        migrations.AlterField(
            model_name="campoformulariopersonalizado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("text", "Texto"),
                    ("textarea", "Área de texto"),
                    ("select", "Selector"),
                    ("number", "Número"),
                    ("date", "Fecha"),
                    ("email", "Email"),
                    ("file", "Archivo"),
                    ("checkbox", "Casilla de verificación"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="creado_por",
            field=models.ForeignKey(
                help_text="Usuario que creó el expediente",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expedientes_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="descripcion",
            field=models.TextField(
                blank=True, help_text="Descripción del expediente (opcional)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="fecha_actualizacion",
            field=models.DateTimeField(
                auto_now=True, help_text="Fecha de última actualización"
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Fecha de creación del expediente"
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="modalidad_monto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compra_directa", "Compra Directa"),
                    ("concurso_invitacion", "Concurso por Invitación"),
                    ("licitacion", "Licitación"),
                    ("adjudicacion_directa", "Adjudicación Directa"),
                ],
                help_text="Modalidad de monto (opcional)",
                max_length=30,
                null=True,
                verbose_name="Modalidad de Monto",
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="numero_expediente",
            field=models.CharField(
                blank=True,
                help_text="Se genera automáticamente si se deja en blanco",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="numero_sima",
            field=models.CharField(
                blank=True,
                help_text="Número o código SIMA asignado al expediente",
                max_length=50,
                null=True,
                verbose_name="Número SIMA",
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="rechazado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que rechazó el expediente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expedientes_rechazados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Rechazado por",
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="subtipo_expediente",
            field=models.CharField(
                blank=True,
                help_text="Subtipo específico que determina qué áreas usar (ej: bienes, servicios, etc.)",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="tipo_adquisicion",
            field=models.CharField(
                choices=[
                    ("bienes", "Bienes"),
                    ("servicios", "Servicios"),
                    ("arrendamientos", "Arrendamientos"),
                ],
                default="bienes",
                help_text="Tipo de adquisición del expediente",
                max_length=20,
                verbose_name="Tipo de Adquisición",
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="titulo",
            field=models.CharField(
                blank=True,
                help_text="Título del expediente (opcional)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historialexpediente",
            name="expediente",
            field=models.ForeignKey(
                blank=True,
                help_text="Expediente relacionado (opcional para actividades del sistema)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial",
                to="digitalizacion.expediente",
            ),
        ),
        migrations.AlterField(
            model_name="notaexpediente",
            name="activa",
            field=models.BooleanField(
                default=True, help_text="Si está visible o archivada"
            ),
        ),
        migrations.AlterField(
            model_name="notaexpediente",
            name="posicion_x",
            field=models.IntegerField(
                default=0, help_text="Posición horizontal en píxeles"
            ),
        ),
        migrations.AlterField(
            model_name="notaexpediente",
            name="posicion_y",
            field=models.IntegerField(
                default=0, help_text="Posición vertical en píxeles"
            ),
        ),
        migrations.AlterField(
            model_name="notificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("mencion", "Mención en Post-it"),
                    ("comentario", "Nuevo Comentario"),
                    ("etapa", "Cambio de Etapa"),
                    ("documento", "Nuevo Documento"),
                    ("asignacion", "Asignación de Expediente"),
                    ("solicitud_registro", "Solicitud de Registro"),
                    ("solicitud_aprobada", "Solicitud Aprobada"),
                    ("usuario_eliminado", "Usuario Eliminado"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="valorareaexpediente",
            name="completada",
            field=models.BooleanField(
                default=False, help_text="Si el área está marcada como completada"
            ),
        ),
    ]
