# Generated by Django 5.0 on 2025-12-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitalizacion", "0019_documentoexpediente_ruta_externa"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoexpediente",
            name="archivo_drive_id",
            field=models.CharField(
                blank=True,
                help_text="ID del archivo en Google Drive",
                max_length=255,
                null=True,
            ),
        ),
    ]
