# Generated by Django 5.0 on 2025-08-09 05:15

import digitalizacion.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=100, unique=True)),
                ("valor", models.TextField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración del Sistema",
                "verbose_name_plural": "Configuraciones del Sistema",
                "ordering": ["clave"],
            },
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documentos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_documento", models.CharField(max_length=50, unique=True)),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "giro",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Ferretería, Papelería",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "fuente_financiamiento",
                    models.CharField(
                        choices=[
                            ("propio_municipal", "Propio Municipal"),
                            ("estatal", "Estatal"),
                            ("federal", "Federal"),
                        ],
                        default="propio_municipal",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_adquisicion",
                    models.CharField(
                        choices=[
                            ("bienes", "Bienes"),
                            ("servicios", "Servicios"),
                            ("arrendamientos", "Arrendamientos"),
                        ],
                        default="bienes",
                        max_length=20,
                    ),
                ),
                (
                    "modalidad_monto",
                    models.CharField(
                        choices=[
                            ("compra_directa", "Compra Directa"),
                            ("concurso_invitacion", "Concurso por Invitación"),
                            ("licitacion", "Licitación"),
                            ("adjudicacion_directa", "Adjudicación Directa"),
                        ],
                        default="compra_directa",
                        max_length=30,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En Proceso"),
                            ("digitalizado", "Digitalizado"),
                            ("verificado", "Verificado"),
                            ("archivado", "Archivado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "archivo_digital",
                    models.FileField(
                        blank=True, null=True, upload_to=digitalizacion.models.upload_to
                    ),
                ),
                (
                    "archivo_original",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("tamaño_archivo", models.PositiveIntegerField(blank=True, null=True)),
                ("fecha_documento", models.DateField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fecha_digitalizacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "palabras_clave",
                    models.TextField(
                        blank=True,
                        help_text="Palabras clave separadas por comas",
                        null=True,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("confidencial", models.BooleanField(default=False)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalizacion.departamento",
                    ),
                ),
                (
                    "digitalizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_digitalizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_verificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalizacion.tipodocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="HistorialDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado_anterior",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "estado_nuevo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="digitalizacion.documento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Documento",
                "verbose_name_plural": "Historiales de Documentos",
                "ordering": ["-fecha"],
            },
        ),
    ]
