# Generated by Django 5.0 on 2025-08-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitalizacion", "0002_alter_documento_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expediente",
            name="numero_sima",
            field=models.CharField(
                blank=True,
                help_text="Número o código SIMA asignado al expediente",
                max_length=50,
                null=True,
                verbose_name="Número SIMA",
            ),
        ),
    ]
