# Generated by Django 5.0 on 2025-08-09 05:55

import digitalizacion.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitalizacion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documento",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Documento (Legacy)",
                "verbose_name_plural": "Documentos (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="historialdocumento",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Historial de Documento (Legacy)",
                "verbose_name_plural": "Historiales de Documentos (Legacy)",
            },
        ),
        migrations.RemoveField(
            model_name="documento",
            name="archivo_original",
        ),
        migrations.AlterField(
            model_name="documento",
            name="archivo_digital",
            field=models.FileField(blank=True, null=True, upload_to="documentos/"),
        ),
        migrations.AlterField(
            model_name="documento",
            name="estado",
            field=models.CharField(default="pendiente", max_length=20),
        ),
        migrations.AlterField(
            model_name="documento",
            name="fuente_financiamiento",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="documento",
            name="giro",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="documento",
            name="modalidad_monto",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="documento",
            name="palabras_clave",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documento",
            name="prioridad",
            field=models.CharField(default="media", max_length=10),
        ),
        migrations.AlterField(
            model_name="documento",
            name="tipo_adquisicion",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="Expediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_expediente", models.CharField(max_length=50, unique=True)),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tipo_expediente",
                    models.CharField(
                        choices=[
                            ("giro", "Por Giro"),
                            ("fuente", "Por Fuente de Financiamiento"),
                            ("tipo_adquisicion", "Por Tipo de Adquisición"),
                            ("monto", "Por Monto"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "giro",
                    models.CharField(
                        blank=True,
                        help_text="Para expedientes por giro",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "fuente_financiamiento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("propio_municipal", "Propio Municipal"),
                            ("estatal", "Estatal"),
                            ("federal", "Federal"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tipo_adquisicion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bienes", "Bienes"),
                            ("servicios", "Servicios"),
                            ("arrendamientos", "Arrendamientos"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "modalidad_monto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("compra_directa", "Compra Directa"),
                            ("concurso_invitacion", "Concurso por Invitación"),
                            ("licitacion", "Licitación"),
                            ("adjudicacion_directa", "Adjudicación Directa"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "estado_actual",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio"),
                            ("solicitud_area", "Solicitud del Área"),
                            ("cotizacion", "Cotización"),
                            ("requisicion_sima", "Requisición SIMA"),
                            ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                            (
                                "aprobacion_director",
                                "Aprobación Director Administrativo",
                            ),
                            ("aprobacion_secretario", "Aprobación Secretario"),
                            (
                                "notificacion_compras",
                                "Notificación a Compras Municipales",
                            ),
                            ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                            ("adjudicacion", "Adjudicación"),
                            ("formalizacion", "Formalización con Orden de Compra"),
                            ("contrato", "Contrato"),
                            ("recepcion_bien", "Recepción del Bien o Servicio"),
                            ("recepcion_facturacion", "Recepción de Facturación"),
                            ("generacion_evidencia", "Generación de Evidencia"),
                            ("envio_compras", "Envío de Expediente a Compras"),
                            ("pago", "Pago"),
                            ("completado", "Completado"),
                        ],
                        default="inicio",
                        max_length=30,
                    ),
                ),
                ("fecha_expediente", models.DateField()),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "palabras_clave",
                    models.TextField(
                        blank=True,
                        help_text="Palabras clave separadas por comas",
                        null=True,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("confidencial", models.BooleanField(default=False)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expedientes_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalizacion.departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expediente",
                "verbose_name_plural": "Expedientes",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio"),
                            ("solicitud_area", "Solicitud del Área"),
                            ("cotizacion", "Cotización"),
                            ("requisicion_sima", "Requisición SIMA"),
                            ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                            (
                                "aprobacion_director",
                                "Aprobación Director Administrativo",
                            ),
                            ("aprobacion_secretario", "Aprobación Secretario"),
                            (
                                "notificacion_compras",
                                "Notificación a Compras Municipales",
                            ),
                            ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                            ("adjudicacion", "Adjudicación"),
                            ("formalizacion", "Formalización con Orden de Compra"),
                            ("contrato", "Contrato"),
                            ("recepcion_bien", "Recepción del Bien o Servicio"),
                            ("recepcion_facturacion", "Recepción de Facturación"),
                            ("generacion_evidencia", "Generación de Evidencia"),
                            ("envio_compras", "Envío de Expediente a Compras"),
                            ("pago", "Pago"),
                            ("completado", "Completado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("nombre_documento", models.CharField(max_length=200)),
                (
                    "archivo",
                    models.FileField(upload_to=digitalizacion.models.upload_to),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("tamaño_archivo", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tipo_archivo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("validado", models.BooleanField(default=False)),
                ("fecha_validacion", models.DateTimeField(blank=True, null=True)),
                (
                    "subido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_validados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="digitalizacion.expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Expediente",
                "verbose_name_plural": "Documentos de Expedientes",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="ComentarioEtapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio"),
                            ("solicitud_area", "Solicitud del Área"),
                            ("cotizacion", "Cotización"),
                            ("requisicion_sima", "Requisición SIMA"),
                            ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                            (
                                "aprobacion_director",
                                "Aprobación Director Administrativo",
                            ),
                            ("aprobacion_secretario", "Aprobación Secretario"),
                            (
                                "notificacion_compras",
                                "Notificación a Compras Municipales",
                            ),
                            ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                            ("adjudicacion", "Adjudicación"),
                            ("formalizacion", "Formalización con Orden de Compra"),
                            ("contrato", "Contrato"),
                            ("recepcion_bien", "Recepción del Bien o Servicio"),
                            ("recepcion_facturacion", "Recepción de Facturación"),
                            ("generacion_evidencia", "Generación de Evidencia"),
                            ("envio_compras", "Envío de Expediente a Compras"),
                            ("pago", "Pago"),
                            ("completado", "Completado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("comentario", models.TextField()),
                ("fecha_comentario", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="digitalizacion.expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario de Etapa",
                "verbose_name_plural": "Comentarios de Etapas",
                "ordering": ["-fecha_comentario"],
            },
        ),
        migrations.CreateModel(
            name="HistorialExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "etapa_anterior",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("etapa_nueva", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="digitalizacion.expediente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Expediente",
                "verbose_name_plural": "Historiales de Expedientes",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="RequisitoEtapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_expediente",
                    models.CharField(
                        choices=[
                            ("giro", "Por Giro"),
                            ("fuente", "Por Fuente de Financiamiento"),
                            ("tipo_adquisicion", "Por Tipo de Adquisición"),
                            ("monto", "Por Monto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subtipo", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio"),
                            ("solicitud_area", "Solicitud del Área"),
                            ("cotizacion", "Cotización"),
                            ("requisicion_sima", "Requisición SIMA"),
                            ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                            (
                                "aprobacion_director",
                                "Aprobación Director Administrativo",
                            ),
                            ("aprobacion_secretario", "Aprobación Secretario"),
                            (
                                "notificacion_compras",
                                "Notificación a Compras Municipales",
                            ),
                            ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                            ("adjudicacion", "Adjudicación"),
                            ("formalizacion", "Formalización con Orden de Compra"),
                            ("contrato", "Contrato"),
                            ("recepcion_bien", "Recepción del Bien o Servicio"),
                            ("recepcion_facturacion", "Recepción de Facturación"),
                            ("generacion_evidencia", "Generación de Evidencia"),
                            ("envio_compras", "Envío de Expediente a Compras"),
                            ("pago", "Pago"),
                            ("completado", "Completado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("nombre_requisito", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("obligatorio", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Requisito de Etapa",
                "verbose_name_plural": "Requisitos de Etapas",
                "ordering": ["tipo_expediente", "etapa", "orden"],
                "unique_together": {
                    ("tipo_expediente", "subtipo", "etapa", "nombre_requisito")
                },
            },
        ),
        migrations.CreateModel(
            name="EtapaExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_etapa",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio"),
                            ("solicitud_area", "Solicitud del Área"),
                            ("cotizacion", "Cotización"),
                            ("requisicion_sima", "Requisición SIMA"),
                            ("suficiencia_presupuestal", "Suficiencia Presupuestal"),
                            (
                                "aprobacion_director",
                                "Aprobación Director Administrativo",
                            ),
                            ("aprobacion_secretario", "Aprobación Secretario"),
                            (
                                "notificacion_compras",
                                "Notificación a Compras Municipales",
                            ),
                            ("valoracion_tipo", "Valoración para Tipo de Adquisición"),
                            ("adjudicacion", "Adjudicación"),
                            ("formalizacion", "Formalización con Orden de Compra"),
                            ("contrato", "Contrato"),
                            ("recepcion_bien", "Recepción del Bien o Servicio"),
                            ("recepcion_facturacion", "Recepción de Facturación"),
                            ("generacion_evidencia", "Generación de Evidencia"),
                            ("envio_compras", "Envío de Expediente a Compras"),
                            ("pago", "Pago"),
                            ("completado", "Completado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("completada", models.BooleanField(default=False)),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "completada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="digitalizacion.expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa de Expediente",
                "verbose_name_plural": "Etapas de Expedientes",
                "ordering": ["expediente", "nombre_etapa"],
                "unique_together": {("expediente", "nombre_etapa")},
            },
        ),
    ]
