# Generated by Django 5.0 on 2025-08-09 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "digitalizacion",
            "0004_expediente_fecha_rechazo_expediente_motivo_rechazo_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contenido",
                    models.TextField(help_text="Contenido de la nota", max_length=500),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("amarillo", "Amarillo"),
                            ("azul", "Azul"),
                            ("verde", "Verde"),
                            ("rosa", "Rosa"),
                            ("naranja", "Naranja"),
                            ("morado", "Morado"),
                        ],
                        default="amarillo",
                        max_length=10,
                    ),
                ),
                (
                    "posicion_x",
                    models.IntegerField(
                        default=0, help_text="Posición horizontal en píxeles"
                    ),
                ),
                (
                    "posicion_y",
                    models.IntegerField(
                        default=0, help_text="Posición vertical en píxeles"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "activa",
                    models.BooleanField(
                        default=True, help_text="Si está visible o archivada"
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        help_text="Documento específico al que se adjunta la nota (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="digitalizacion.documentoexpediente",
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="digitalizacion.expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Expediente",
                "verbose_name_plural": "Notas de Expedientes",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
